/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;

/**
 *
 * @author NAURA SHARFINA AZARINE!!!
 */
public class CobaNormanDkk extends javax.swing.JFrame {

    /**
     * Creates new form NormanDkk
     */
    public CobaNormanDkk() {
        initComponents();
        jScrollPane1.getViewport();
        setLocationRelativeTo(null);
        //Emma
        SetterGetter anak1 = new SetterGetter();
        anak1.setNama("Emma");
        anak1.setUmur("12");
        anak1.setGoldar("O");
        anak1.setJenisKelamin("Perempuan");
        anak1.setTanggall("22 Agustus 2034");
        anak1.setTinggi("145");
        
        Nama.setText(String.valueOf(anak1.getNama()));
        Umur.setText(String.valueOf(anak1.getUmur()));
        Goldar.setText(String.valueOf(anak1.getGoldar()));
        JenisKelamin.setText(String.valueOf(anak1.getJenisKelamin()));
        Tanggal.setText(String.valueOf(anak1.getTanggall()));
        Tinggi.setText(String.valueOf(anak1.getTinggi()));
     
        //Norman
        SetterGetter anak2 = new SetterGetter();
        anak2.setNama("Norman");
        anak2.setUmur("12");
        anak2.setGoldar("B");
        anak2.setJenisKelamin("Laki - Laki");
        anak2.setTanggall("21 Maret 2034");
        anak2.setTinggi("145");
        
        Nama3.setText(String.valueOf(anak2.getNama()));
        Umur3.setText(String.valueOf(anak2.getUmur()));
        Goldar3.setText(String.valueOf(anak2.getGoldar()));
        JenisKelamin3.setText(String.valueOf(anak2.getJenisKelamin()));
        Tanggal3.setText(String.valueOf(anak2.getTanggall()));
        Tinggi3.setText(String.valueOf(anak2.getTinggi()));
        
        //Ray
        SetterGetter anak3 = new SetterGetter();
        anak3.setNama("Ray");
        anak3.setUmur("12");
        anak3.setGoldar("A");
        anak3.setJenisKelamin("Laki - Laki");
        anak3.setTanggall("15 Januari 2034");
        anak3.setTinggi("150");
        
        Nama2.setText(String.valueOf(anak3.getNama()));
        Umur2.setText(String.valueOf(anak3.getUmur()));
        Goldar2.setText(String.valueOf(anak3.getGoldar()));
        JenisKelamin2.setText(String.valueOf(anak3.getJenisKelamin()));
        Tanggal2.setText(String.valueOf(anak3.getTanggall()));
        Tinggi2.setText(String.valueOf(anak3.getTinggi()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.JLabel();
        Umur = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Goldar = new javax.swing.JLabel();
        Tinggi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Nama3 = new javax.swing.JLabel();
        JenisKelamin3 = new javax.swing.JLabel();
        Umur3 = new javax.swing.JLabel();
        Tanggal3 = new javax.swing.JLabel();
        Goldar3 = new javax.swing.JLabel();
        Tinggi3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tambah = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        JenisKelamin2 = new javax.swing.JLabel();
        Umur2 = new javax.swing.JLabel();
        Tanggal2 = new javax.swing.JLabel();
        Goldar2 = new javax.swing.JLabel();
        Tinggi2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BG2 = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_cancel_30px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_back_to_30px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Daftar Anak");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_rotate_page_counterclockwise_30px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 30));

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jenis Kelamin ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Umur");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tanggal Lahir");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Golongan Darah");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tinggi Badan ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, 20));

        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText(":");
        Nama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        JenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        JenisKelamin.setText(":");
        jPanel3.add(JenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        Umur.setForeground(new java.awt.Color(255, 255, 255));
        Umur.setText(":");
        jPanel3.add(Umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        Tanggal.setText(":");
        jPanel3.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, 20));

        Goldar.setForeground(new java.awt.Color(255, 255, 255));
        Goldar.setText(":");
        jPanel3.add(Goldar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, 20));

        Tinggi.setForeground(new java.awt.Color(255, 255, 255));
        Tinggi.setText(":");
        jPanel3.add(Tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/Emma_on.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, 240));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nama");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 900, -1, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Jenis Kelamin ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, -1, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Umur");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 940, -1, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tanggal Lahir");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1060, -1, 20));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Golongan Darah");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 980, -1, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Tinggi Badan ");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1100, -1, 20));

        Nama3.setForeground(new java.awt.Color(255, 255, 255));
        Nama3.setText(":");
        Nama3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(Nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 900, -1, -1));

        JenisKelamin3.setForeground(new java.awt.Color(255, 255, 255));
        JenisKelamin3.setText(":");
        jPanel3.add(JenisKelamin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1020, -1, -1));

        Umur3.setForeground(new java.awt.Color(255, 255, 255));
        Umur3.setText(":");
        jPanel3.add(Umur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 940, -1, -1));

        Tanggal3.setForeground(new java.awt.Color(255, 255, 255));
        Tanggal3.setText(":");
        jPanel3.add(Tanggal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1060, -1, 20));

        Goldar3.setForeground(new java.awt.Color(255, 255, 255));
        Goldar3.setText(":");
        jPanel3.add(Goldar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 980, -1, 20));

        Tinggi3.setForeground(new java.awt.Color(255, 255, 255));
        Tinggi3.setText(":");
        jPanel3.add(Tinggi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1100, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/Norman_on (1).png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 180, 240));

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        jPanel3.add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1710, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nama");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1470, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Jenis Kelamin ");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1590, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Umur");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1510, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tanggal Lahir");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1630, -1, 20));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Golongan Darah");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1550, -1, 20));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Tinggi Badan ");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1670, -1, 20));

        Nama2.setForeground(new java.awt.Color(255, 255, 255));
        Nama2.setText(":");
        Nama2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(Nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1470, -1, -1));

        JenisKelamin2.setForeground(new java.awt.Color(255, 255, 255));
        JenisKelamin2.setText(":");
        jPanel3.add(JenisKelamin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1590, -1, -1));

        Umur2.setForeground(new java.awt.Color(255, 255, 255));
        Umur2.setText(":");
        jPanel3.add(Umur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1510, -1, -1));

        Tanggal2.setForeground(new java.awt.Color(255, 255, 255));
        Tanggal2.setText(":");
        jPanel3.add(Tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1630, -1, 20));

        Goldar2.setForeground(new java.awt.Color(255, 255, 255));
        Goldar2.setText(":");
        jPanel3.add(Goldar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1550, -1, 20));

        Tinggi2.setForeground(new java.awt.Color(255, 255, 255));
        Tinggi2.setText(":");
        jPanel3.add(Tinggi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1670, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/Ray-Anime.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1190, 180, 240));

        BG2.setBackground(new java.awt.Color(0, 0, 0, 80));
        BG2.setOpaque(true);
        jPanel3.add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 910, 1800));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/wp3951108 (1).jpg"))); // NOI18N
        BG1.setOpaque(true);
        jPanel3.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 910, -1));

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel16MousePressed
    int xx, xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
        this.hide();
        Beranda balik = new Beranda();
        balik.setVisible(true);
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        new DaftarAnak().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TambahActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.hide();
        NormanDkk balik = new NormanDkk();
        balik.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobaNormanDkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobaNormanDkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobaNormanDkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobaNormanDkk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
                new CobaNormanDkk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel BG2;
    public javax.swing.JLabel Goldar;
    public javax.swing.JLabel Goldar2;
    public javax.swing.JLabel Goldar3;
    public javax.swing.JLabel JenisKelamin;
    public javax.swing.JLabel JenisKelamin2;
    public javax.swing.JLabel JenisKelamin3;
    public javax.swing.JLabel Nama;
    public javax.swing.JLabel Nama2;
    public javax.swing.JLabel Nama3;
    private javax.swing.JButton Tambah;
    public javax.swing.JLabel Tanggal;
    public javax.swing.JLabel Tanggal2;
    public javax.swing.JLabel Tanggal3;
    public javax.swing.JLabel Tinggi;
    public javax.swing.JLabel Tinggi2;
    public javax.swing.JLabel Tinggi3;
    public javax.swing.JLabel Umur;
    public javax.swing.JLabel Umur2;
    public javax.swing.JLabel Umur3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
